version: 2
updates:
  # npm 依赖检查
  - package-ecosystem: "npm"
    directory: "/po-translator-gui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    
  # Rust 依赖检查
  - package-ecosystem: "cargo"
    directory: "/po-translator-gui/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    
  # GitHub Actions 依赖检查
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci/cd"

