name: Check

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache npm dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-20-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-20-
            ${{ runner.os }}-node-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: 'po-translator-gui/src-tauri -> target'

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        working-directory: ./po-translator-gui
        run: npm ci

      - name: Run frontend linter
        working-directory: ./po-translator-gui
        run: npm run lint || true

      - name: Run Rust format check
        working-directory: ./po-translator-gui/src-tauri
        run: cargo fmt --all -- --check

      - name: Run Rust clippy
        working-directory: ./po-translator-gui/src-tauri
        run: |
          # 只检查严重问题（正确性和可疑代码），允许性能优化建议和代码风格警告
          cargo clippy -- \
            -D clippy::correctness \
            -D clippy::suspicious \
            -A dead_code \
            -A clippy::perf \
            -A clippy::style \
            -A clippy::complexity

      - name: Run Rust tests
        working-directory: ./po-translator-gui/src-tauri
        run: cargo test
