name: Check

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: 'po-translator-gui/src-tauri -> target'

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: npm ci
        working-directory: po-translator-gui

      - name: Run frontend linter
        run: npm run lint || true
        working-directory: po-translator-gui

      - name: Run Rust format check
        run: cargo fmt --all -- --check
        working-directory: po-translator-gui/src-tauri

      - name: Run Rust clippy
        run: cargo clippy -- -D warnings
        working-directory: po-translator-gui/src-tauri

      - name: Run Rust tests
        run: cargo test
        working-directory: po-translator-gui/src-tauri
